apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: ingress-nginx-admission
webhooks:
  - name: validate.nginx.ingress.kubernetes.io
    clientConfig:
      service:
        name: ingress-nginx-controller-admission
        namespace: ingress-nginx
        path: "/networking/v1/ingresses"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTVENDQWpHZ0F3SUJBZ0lVRjlRaUpmZmFmL3dGQ0xxSTUzZWxYTXJQRFZVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd05ERXlNREFHQTFVRUF3d3BhVzVuY21WemN5MXVaMmx1ZUMxaFpHMXBjM05wYjI0dWFXNW5jbVZ6Y3kxdQpaMmx1ZUM1emRtTXdIaGNOTWpVd01qSTRNVE14TnpBeldoY05Nall3TWpJNE1UTXhOekF6V2pBME1USXdNQVlEClZRUUREQ2xwYm1keVpYTnpMVzVuYVc1NExXRmtiV2x6YzJsdmJpNXBibWR5WlhOekxXNW5hVzU0TG5OMll6Q0MKQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNNzhGVnJuUXNTVDBQMGMxZWFReStVNwpRbUkvUnI2VUlHakkvVDNqT2F0czJYZDIxR3VWT3JrV0hQTGhCSjVTQlVreGhIU2czV3dXbWhlMkd4NmQxU0NXCnk3NWpiNTV0RmpzUGQ2ZXJIRURKU1l3VkJlM1RDeHdpUHphd2h5Yi9Bd1U1S3F5cVBJaytST2NlbTdoQTF4WDUKelk3R2o4VEtOaVp1blpnN1B2L1U4bDhEQTVvYXBLZks1LzBmVHh2NFdYZzJldTNENk9Wd3JveXo5Z1VJczAyegpMZnV5cFlYWjVSZXIrVndmR1RCcjlvM09VU095NTFLTVV1OStZTG4zQzdZT2EwTlN0cjRpQmRPTGpHQmJzb29JCm1Bd2labXl0a2Y5RGNKT05xL0JDYWx3ZmNjbXNQTTNtMlpDYVhSZWVvQ0dyR2JubGNpMy94ZzV3T1FVb1FyRUMKQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkFISHpBTjBHdng0Q1lYUlRCS1Zxb3hFT3VkTE1COEdBMVVkSXdRWQpNQmFBRkFISHpBTjBHdng0Q1lYUlRCS1Zxb3hFT3VkTE1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJCmh2Y05BUUVMQlFBRGdnRUJBRkp2TE40M29uQTlreWtlNkZUMDJKM0M0SXBuSTVPWktpeFBlR3E1eWNxemRaakMKNFRUTHZ3a1p3YlpLRm1vclhmYWR6YTdpYkY5RGlSMWNFNWJIek5IRDFZWmJqaXQ5NytTM0FmVXBzam9wOTMyWQpFQ2dZVjVVZ3ROSDFRZFd4ZjFDTUJReVFVZXJWcmxaQmdQSzlkaUpsTm0vZ3FVZEZNNVhPVHMxMmIrbEcxRUZmCkNNL1ZMblZ6VlB0VXVudnUzbVZ1ZnBtL1h4SXZiMHdENXNrQ3B3d1h5VjI0YzkvNkRjVVdrcU0yR0NwdUZYUFcKSENSb3p5UHprSzdOeHlsZ1FRL3V1ZjZzOWV4bHh2eGF6TVpCWDVjR3FPRGhNVU9FZHMvYXJxQlVIWWZMT1hTcgo1Mks0Q3BPdy9Vc01iRHhVLytWVmVJUlVKakN6Y2dxbWtBTUlxTDA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K  # Replace with actual CA bundle if needed
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1"]
        resources: ["ingresses"]
    admissionReviewVersions: ["v1"]
    sideEffects: None

